trigger:
  - main

pool:
  name: 'Self-Hosted'
  demands:
    - agent.name -equals nhk-VMware-Virtual-Platform

steps:
  - script: echo "Running on self-hosted agent" >> /home/nhk/Desktop/agent.log
    displayName: 'Hello World'
