trigger:
  - main

pool:
  name: 'Self-Hosted'
  demands:
    - agent.name -equals nhk-VMware-Virtual-Platform

jobs:
  - job: Test
    steps:
      # Install Node.js
      - task: UseNode@1
        inputs:
          version: "20.19.6"
        displayName: 'Install Node.js'


      - script: |
          npm install
          ls -al node_modules
        workingDirectory: $(System.DefaultWorkingDirectory)/frontend/
        displayName: 'Install Frontend dependencies'


      - script: |
          npm test -- --watchAll=false
        workingDirectory: $(System.DefaultWorkingDirectory)/frontend/
        displayName: 'Run Frontend Tests'

      # Install Java
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '21'
        displayName: 'Install Java 21'

      - script: |
          ./mvnw test
        workingDirectory: $(System.DefaultWorkingDirectory)/backend/
        displayName: 'Run Backend Tests'  