trigger:
  - main

pool:
  name: 'Self-Hosted'
  demands:
    - agent.name -equals nhk-VMware-Virtual-Platform

jobs:
  - job: Test

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: my_database
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
        ports:
          - 5432:5432

    steps:
      # Install Node.js
      - task: UseNode@1
        inputs:
          version: "20.19.6"
        displayName: 'Install Node.js'

      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(System.DefaultWorkingDirectory)/frontend/node_modules
        displayName: 'Cache npm dependencies'

      - script: |
          npm install
          ls -al node_modules
        workingDirectory: $(System.DefaultWorkingDirectory)/frontend/
        displayName: 'Install Frontend dependencies'

      - script: |
          npm test -- --watchAll=false
        workingDirectory: $(System.DefaultWorkingDirectory)/frontend/
        displayName: 'Run Frontend Tests'

      # # Install Java
      # - task: JavaToolInstaller@0
      #   inputs:
      #     versionSpec: '21'
      #     jdkArchitectureOption: 'x64'
      #     jdkSourceOption: 'AzureJDK'
      #   displayName: 'Install Java 21'

      - script: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done
          echo "Postgres is ready!"
        displayName: 'Wait for Postgres'

      - script: |
          ./mvnw test
        workingDirectory: $(System.DefaultWorkingDirectory)/backend/
        displayName: 'Run Backend Tests'  

